### ISSUE TITLE
Move CommitOrderCalculator to Common

### ISSUE THREAD

**Issue by nfx** [doctrine/common#201] opened 2012-10-08 16:17 UTC
What exists now:

* https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Internal/CommitOrderCalculator.php
* https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/CommitOrderCalculator.php

Almost with the same content. 

What is desired:

* in order not to create new JPA implementation based on doctrine-common, as a developer i won't need to copy-paste a class from there.

**Comment by guilhermeblanco** [comment] 2016-03-27 03:04
-1, closing.

**Closed by guilhermeblanco** 2016-03-27 03:04 UTC

**Comment by Ocramius** [comment] 2016-11-30 17:11
Removed milestone, since the issue is a `won't fix`
