### ISSUE TITLE
rename error in ProxyGenerator

### ISSUE THREAD

**Issue by Draeli** [doctrine/common#327] opened 2014-07-14 12:53 UTC
Hello,

Actually, I have this hapening, I don't have idea why, I give you my backtrace, this not happen each time I refresh page but some time.

``` php
( ! ) Warning: rename(/app/cache/dev/doctrine/orm/Proxies\__CG__MyCommonBundleEntityVisibilityInformation.php.53c3cccd0a5415.53070441,/app/cache/dev/doctrine/orm/Proxies\__CG__MyCommonBundleEntityVisibilityInformation.php): in \vendor\doctrine\common\lib\Doctrine\Common\Proxy\ProxyGenerator.php on line 305
```

backtrace :

```
Call Stack
#   Time    Memory  Function    Location
18  0.6984  11450624    Doctrine\ORM\EntityRepository->findOneBy( ) ..\UserManager.php:68
19  0.7052  11784056    Doctrine\ORM\Persisters\BasicEntityPersister->load( )   ..\EntityRepository.php:196
20  0.7709  12390192    Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll( ) ..\BasicEntityPersister.php:756
21  0.7709  12390280    Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData( ) ..\AbstractHydrator.php:140
22  0.7710  12395136    Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData( ) ..\SimpleObjectHydrator.php:48
23  0.7715  12411464    Doctrine\ORM\UnitOfWork->createEntity( )    ..\SimpleObjectHydrator.php:138
24  0.7869  12653744    Doctrine\Common\Proxy\AbstractProxyFactory->getProxy( ) ..\UnitOfWork.php:2676
25  0.7869  12653832    Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition( )   ..\AbstractProxyFactory.php:119
26  0.7882  12666032    Doctrine\Common\Proxy\ProxyGenerator->generateProxyClass( ) ..\AbstractProxyFactory.php:218
27  0.7930  12695936    rename ( )  ..\ProxyGenerator.php:305
```

**Comment by brunowego** [comment] 2015-03-12 19:23
+1

**Comment by diegopso** [comment] 2015-10-07 21:04
+1

**Comment by chielsen** [comment] 2016-01-11 14:07
+1

**Comment by ragboyjr** [comment] 2016-02-12 08:49
:+1:

**Comment by Apezoumon123** [comment] 2016-09-23 08:06
somebody help me i have the same problem

**Comment by anuragdalia** [comment] 2016-10-27 22:58
+1

**Comment by camilom** [comment] 2016-10-31 20:04
I have the same problem

Warning: rename : Acceso denegado. (code: 5)
in vendor\doctrine\common\lib\Doctrine\Common\Proxy\ProxyGenerator.php at line 306

306 line: `rename($tmpFileName, $fileName);`

Help pls

**Comment by nickrouty** [comment] 2017-03-30 16:18
I found this thread to be helpful in tracking down a solution:
[See doctrine issue 2907](https://github.com/doctrine/doctrine2/issues/2907)

It talks about the issue generally creeping up when concurrent requests are made, which was the case in my scenario.

You can then look at the advanced configuration in Doctrine docs, this also helped:
[Doctrine Advanced Configuration](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/advanced-configuration.html)

I ended up setting a configuration setting to set the generate_proxies config param to:
Doctrine\Common\Proxy\AbstractProxyFactory::AUTOGENERATE_FILE_NOT_EXISTS

This will ensure that the file only generates if it doesn't exist yet. Note that this could create problems for you if you update your models/entities and do not clear out the proxy classes cached.

**Comment by solody** [comment] 2017-06-23 07:54
same problem +1

**Comment by Majkl578** [comment] 2017-06-23 13:04
Note that for production environment you should *always* pre-generate the proxies (i.e. on your CI) to not rely on lazy generation (which is prone to race conditions).

**Comment by zayanit** [comment] 2017-12-06 16:19
+1 same problem

**Comment by alcaeus** [comment] 2017-12-07 15:59
I'm going to close this as `invalid`. The issue described by OP is caused by the operating system. The only way I've managed to reproduce it was in a Docker machine where `rename('a/file.tmp', 'a/file');` caused a cross-device rename due to the union filesystem in use there, and even then I didn't get it to consistently break.

Without at least a consistent way to reproduce this, there's nothing for us to fix. So please, instead of being the next person to add a `+1` type comment, please provide information that is not yet present or try to build a reproducible test case for the problem. Thank you!

**Closed by alcaeus** 2017-12-07 15:59 UTC

**Comment by ppamment** [comment] 2018-02-16 15:57
Hi @alcaeus 

I think I can help here. We recently updated our Symfony/Doctrine MVC application to use an API driven React frontend. All of a sudden this issue starts popping up on some machines.

Why could that be?
MVC application was making single requests at a time when in dev mode, where we have proxy class generation set to AUTOGENERATE_ALWAYS, which is not something we want to change as it is the most convenient setting.
The new React frontend is making multiple async requests to the Sf/Doctrine backend, and suddenly we get a race condition where a couple of these backend requests are generating and trying to write to that proxy file at the same time.

I tried adding an @ suppressor before the rename call in vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:309 and the problem goes away. I can't say this is the best solution since it is true that you are now not using the newly generated proxy class, but IMO a race condition with proxy generation set to AUTOGENERATE_ALWAYS and concurrent requests is not just possible, but expected and should be addressed. PHP rename function is known to be not race condition safe and this needs to be addressed if you wish to avoid such issues.

In terms of how to reproduce, I would bet that firing ab against a simple doctrine instance with AUTOGENERATE_ALWAYS will do the job (note, im running windows, it's possible other filesystems handle this better than ntfs).

For now I can get by with the @ suppressor. It's not as though I actually need my proxy classes to be regenerated for both of the 2 requests that are milliseconds apart. If I have the time to look into how to make the rename race condition safe I may see if I can put together a PR.

**Comment by alcaeus** [comment] 2018-02-20 06:49
@ppamment the issue you described is exactly the scenario we don't want to fix by error suppression but rather with cache warmup: you should use `AUTOGENERATE_NEVER` in high-load conditions as described and pre-warm the cache before sending requests there.

**Comment by ppamment** [comment] 2018-02-20 08:50
@alcaeus like I said I don't think the suppressor is the correct solution either. I'm just saying that it is useful to help pin down the route cause and in my case it's an acceptable solution while developing (much as it goes against my instincts to make a temporary edit to a composer installed vendor package). At least when these things get pushed out to our public servers the suppressor is gone and the proxies are as you suggested pregenerated.  

On the other hand I hope you'd agree my own dev machine, receiving at most a few concurrent requests from my locally running frontend is not what you'd call a high load environment. Of course I can set AUTOGENERATE_NEVER but this is not very convenient when developing on your own machine as you then need to regenerate proxies every time you edit an entity which is not very good DX.
There is some information on stackoverflow about how to do a race condition safe rename. I will investigate if I get the time.

Thanks

**Comment by Ocramius** [comment] 2018-02-20 08:51
If you need a local dev environment, AUTOGENERATE_EVAL works good enough

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by ppamment** [comment] 2018-02-20 08:51
Root cause*

**Comment by ppamment** [comment] 2018-02-20 09:07
Thanks @Ocramius I hadn't really looked into that option, but I can't see any reason this strategy wouldn't work for local development. It's probably even faster than AUTOGENERATE_ALWAYS as it doesn't hit the disk.
I do like the comment too :)

"
     * This strategy is only sane for development, and even then it gives me
     * the creeps a little.
"
