### ISSUE TITLE
FileCache and inode issue

### ISSUE THREAD

**Issue by broncha** [doctrine/common#354] opened 2015-02-18 13:16 UTC
Hi, 

I would not label this as an issue, but the way filecache are stored in disk, got me scratching my head for a while. I looked at the code

```
protected function getFilename($id)
    {
        return $this->directory
            . DIRECTORY_SEPARATOR
            . implode(str_split(hash('sha256', $id), 2), DIRECTORY_SEPARATOR)
            . DIRECTORY_SEPARATOR
            . preg_replace($this->disallowedCharacterPatterns, $this->replacementCharacters, $id)
            . $this->extension;
    }
```

This creates 32 directories and a cache file. A total of 33 inodes being used for one cache. I just hit an issue in our servers. `df` was showing 70% disk free, but could not upload any images. After digging in, I found that all the inodes were used up. Digging in more, turns out the nonce cache we used with escapestudiowssebundle were using up all the inodes. 

I have changed the nonce store to redis cache now, but I think the implementation for filecache should be less inode intensive. 33 inodes for 1 cache file is too much IMO.

**Comment by Ocramius** [comment] 2015-02-18 17:00
Dupe of doctrine/cache#63.

Also, as noted in the linked issue, using the file cache in production is madness.

**Closed by Ocramius** 2015-02-18 17:00 UTC

**Comment by jkobus** [comment] 2015-09-10 10:46
The problem with nodes happens very often. It's also very hard to find what is the problem when it happens. I don't agree with you saying that "you should not use this anyway so we don't need to look into that issue".
