### ISSUE TITLE
Criteria/collection::matching() not transforming property name to column name

### ISSUE THREAD

**Issue by martixy** [doctrine/common#801] opened 2017-06-15 10:44 UTC
On `doctrine/common v2.6.2` / `doctrine/dbal v2.5.5`

Say you have
```PHP
/**
 * @ORM\Entity(repositoryClass="UserRepository")
 * @ORM\Table(name="user")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Post", mappedBy="user")
     */
    private $posts;
}
```
```PHP
/**
 * @ORM\Table(name="posts")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="posts")
     */
    private $user;

    /**
     * @ORM\Column(type="boolean", nullable=false, options={"default":0})
     */
    private $isHidden;
}
```

And say you get a user and want to take all the hidden posts:
`$user->getPosts()->matching(Criteria::create()->where(Criteria::expr()->eq('isHidden', true)))`
Well... nothing anywhere transforms the property name to the actual column name and you get doctrine trying to execute a query with an invalid column name.

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'te.isHidden' in 'where clause'`

**Comment by Ocramius** [comment] 2017-06-15 14:30
What's the column name? From your mappings, `isHidden` looks like the correct name.

**Comment by martixy** [comment] 2017-06-15 15:59
Well, as normal without an explicit column name, doctrine turns `camelCase` property names to `underscore_case` column names.

So `isHidden` -> `is_hidden`.

Problem being, that this transformation from property name to column name doesn't happen in the case, meaning we get a query with the property name, instead of its associated column name.

**Comment by Ocramius** [comment] 2017-06-15 16:40
Uhm, doctrine doesn't do the transformation by default: a naming strategy must be set to do that. The [`DefaultNamingStrategy`](https://github.com/doctrine/doctrine2/blob/fc67b398a1efd3d61837778e2cda2d05a395778c/lib/Doctrine/ORM/Mapping/DefaultNamingStrategy.php#L50) uses an identity function.

Could this be reproduced in isolation in a [functional test case](https://github.com/doctrine/doctrine2/tree/971c40002522cfebe58d80aff21eef9fe439fa60/tests/Doctrine/Tests/ORM/Functional)?

**Comment by martixy** [comment] 2017-06-15 19:00
Having used doctrine only as part of symfony, I assumed that was the default naming strategy. However it seems that symfony imposes its own default naming strategy upon doctrine.

As for an actual test... I'm not familiar with the entire procedure, which means if I were to write it, it will require time which I do not have this month.

**Comment by paulj3** [comment] 2018-10-08 14:48
@Ocramius / @martixy - Do either of you know if this has been addressed in newer versions of collections? We have a lot of getters that we have modified with `hasBooleanProperty()` instead of the symfony default `isBooleanProperty()`

**Closed** 2024-05-15 15:12 UTC
Labels: Bug
