### ISSUE TITLE
Fixed error for windows file length limitation.

### ISSUE THREAD

**Issue by FabianPiconeDev** [doctrine/common#703] opened 2015-12-15 09:28 UTC
Can you please publish this fix? See https://github.com/FabianPiconeDev/cache/commit/df295ba72839e841e2f8302194ee2f64beb08ff5

Fixed error for windows file length limitation.
There was logical and string length comparsion error.

**Comment by Ocramius** [comment] 2015-12-15 12:11
Closing as duplicate of doctrine/cache#113

**Closed by Ocramius** 2015-12-15 12:11 UTC
