### ISSUE TITLE
Attempted to call an undefined method named "__set_state" of class "Doctrine\ORM\Mapping\InheritanceType"

### ISSUE THREAD

**Issue by kniziol** [doctrine/common#385] opened 2015-10-08 15:51 UTC
#### WTF?
Take a look at details below.

##### Exception:
```php
UndefinedMethodException in [My-ExtraBundle-Entity-User-[Annot]][1].doctrinecache.php line 6:
Attempted to call an undefined method named "__set_state" of class "Doctrine\ORM\Mapping\InheritanceType"
```

##### Versions of libraries
* doctrine/orm: 2.4.8
* symfony/symfony: 2.8.0-DEV

##### Entity
```php
<?php

namespace My\ExtraBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * User
 *
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discriminator_type", type="string")
 *
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass="My\ExtraBundle\Repository\UserRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 */
class User
{
    ...
```

##### composer.json
```json
    ...
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "~2.7@dev",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    },
    ...
```

**Comment by stof** [comment] 2015-10-08 16:03
this is a bug in Symfony 2.8-dev, which uses the PhpFileCache to store things it does not support. there is a PR opened on Symfony to fix this.
See https://github.com/symfony/symfony/issues/16168 for the bug report and https://github.com/symfony/symfony/pull/16173 for the PR proposing a fix.

I'm closing this issue as it is not a bug in doctrine/common

**Closed by stof** 2015-10-08 16:03 UTC

**Comment by kniziol** [comment] 2015-10-08 16:09
Thanks for explanation
